### ISSUE TITLE
ES6 'import' formating 

### ISSUE THREAD

**Issue by geakstr** [enginespot/js-beautify-sublime#29]
Please update js-beautify lib for fixing this issue [https://github.com/beautify-web/js-beautify/issues/382](https://github.com/beautify-web/js-beautify/issues/382)

**Comment by thelinuxlich** [comment]
+1 this sux

**Comment by mtsr** [comment]
+1

**Comment by glennr** [comment]
+1

**Comment by vasconita** [comment]
+1

**Comment by dmoreno** [comment]
+1

**Comment by ddemolina** [comment]
+1

**Comment by fmarin** [comment]
+1

**Comment by enginespot** [comment]
I am busy with another project , so can somebody add pr pls 

Thanks.

**Comment by enginespot** [comment]
js beautify update to 1.6.4, it should fixed the bug
