### ISSUE TITLE
js-beautify stopped working Sublime Text 3 (Build 3083)

### ISSUE THREAD

**Issue by karthilxg** [enginespot/js-beautify-sublime#40]
I'm using `Sublime Text 3 ( Build 3083)`, `jsbeautifier` stopped working. I tried reinstalling through `Package Control`, tried both command line shortcut's and menu option to run the beautifier still didn't work. Any help would be appreciated.

**jsbeautifier version:**

![image](https://cloud.githubusercontent.com/assets/3691228/11909666/ee0dfc4a-a59e-11e5-81ea-f51c53af2de2.png)

Sublime settings as follows,

```js
{
  "indent_size": 4,
  "indent_char": " ",
  "indent_level": 0,
  "indent_with_tabs": false,
  "preserve_newlines": true,
  "max_preserve_newlines": 10,
  "jslint_happy": false,
  "brace_style": "collapse",
  "keep_array_indentation": false,
  "keep_function_indentation": false,
  "space_before_conditional": true,
  "break_chained_methods": false,
  "eval_code": false,
  "unescape_strings": false,
  "wrap_line_length": 0,

  // jsbeautify options
  "format_on_save": false,
  "use_original_indentation": false
}
```

```js
[{
    "keys": ["ctrl+alt+f"],
    "command": "jsbeautify",
    "context": [{
        "key": "selector",
        "operator": "equal",
        "operand": "source.js,source.json,source.jade"
      }
    ]
  }
]
```

**Comment by andyhqtran** [comment]
Doesn't work on my end either.

**Comment by endquote** [comment]
See #39

**Comment by nfantone** [comment]
Same over here on 3095.

**Comment by pratik60** [comment]
@enginespot Hey, we are using a fork version of this. If you have any pointers as to what broke it, do suggest, so we can attempt to initiate a pull request

**Comment by enginespot** [comment]
yes yes , welcome

**Comment by mattblang** [comment]
Was anything figured out regarding this issue? It seems that with the current versions of this package and ST3, beautify doesn't work correctly.

**Comment by tc-mccarthy** [comment]
Beautify stopped working for me in the last few days as well.

**Comment by tommymessbauer** [comment]
The latest September build of ST3 also broke this plugin for me. Can I help in any way to fix it?

**Comment by enginespot** [comment]
Thanks everyone ,currently I will take some time to fix all of the bugs ,and tried to add new features

**Comment by enginespot** [comment]
please try to use the latest version

**Comment by enginespot** [comment]
bug fixed with the latest version
