### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by fake-name** [enginespot/js-beautify-sublime#43]
I'm trying to find a *stand alone* JS beautifier that *doesn't* require an entire node installation, principally because I need to just clean up a few files.

Can you actually document what this plugin requires? From the fact that it's a wrapper, I assume it calls an external binary, but there are *lots* of "js beautifier" tools out there.

**Comment by Lexicality** [comment]
A bit late in getting back to you, but this plugin is fully self contained and runs the Python version of [js-beautify](https://github.com/beautify-web/js-beautify) inside Sublime's python interpreter.
All you need to do is install it and it works.
